### PR TITLE
Fixed #2 - error handling on the database file

### LINKED ISSUE #2: Exception when Database is Locked

### PR DESCRIPTION
**Pull request by mpentler**
Fixed #2

Added error handling for the initial access of the database. This should catch any access issues, print the error and then exit with a failed return code.

You may want to do more error handling than this in the future, but for now it fixes your issue I think. I'm specifically finding easy bugs to squish to contribute to the community.

### CODE REVIEW

**Comment by brannondorsey** [comment]
Thanks for this!

**Comment by brannondorsey** [comment]
Hey @mpentler, I just noticed that you are printing errors to stdout, however, only paste IDs should be printed to stdout (more in the [README](https://github.com/mpentler/pastebin-mirror#output-to-stdout-and-stderr)). Would you mind submitting a PR that changes the print statements you added to use stdout?

**Comment by brannondorsey** [comment]
This can be done so like [this](https://github.com/brannondorsey/pastebin-mirror/blob/master/pastebin-mirror/__main__.py#L50).

**Comment by mpentler** [comment]
Of course! Good spot. I did mean to check with you because I’d noticed that but didn’t realise you had a system ;-)

I’ve already overhauled this per https://github.com/mpentler/pastebin-mirror/issues/1 though so I can change them in that?

**Comment by mpentler** [comment]
Fucked up, didn’t I? Went and pushed some more changes already, didn’t I? 😞

**Comment by brannondorsey** [comment]
Yeah, they've already been merged the way you had them, but that's ok. Just create a new PR with your other changes that keeps all output that isn't a paste ID writing to stdout.

**Comment by mpentler** [comment]
Btw what I meant by my last comment was that I’d pushed more work to my master branch since pushing these changes without the stderr’s in. But it’ll all be sorted with the other open PR and the subsequent one I’ll submit next week.

**Pull request merged**
