### PR TITLE
Partially addresses #1 #2 & #3

### PR DESCRIPTION
**Pull request by mpentler**
Ok, how is this? It adds your stderr fixes, and goes some way to adding:

- Error checking back in main where it belongs
- Quiet option added and working (a bit)
- Basic count of session stats 

Have a look at this, see what you think. I’m happy with it on mine. :)

### CODE REVIEW

**Comment by mpentler** [comment]
And of course it’s tagged the wrong repo’s issues - I’ll figure this out eventually...

**Comment by mpentler** [comment]
Obviously it needs a bit more on the error checking than this, but the purpose of this PR is primarily the stderr fixes. I’ll actually finish the rest before the next PR :

**Comment by mpentler** [comment]
(Sorry, I tend to post a lot)

- SQL/Flatfile error checking is done so I've pushed it so it'll be in this PR

**Comment by mpentler** [comment]
Wanted to look at scraper but not sure what to do with it. Those Exceptions could probably do with being a bit more specific but I’m not sure what to check for. Guess I’ll go look up the requests documentation! ;-)

**Comment by mpentler** [comment]
@brannondorsey Brannon, for now please leave this open. I’ve kinda fucked up doing all the stuff I’ve done in master and my repo is radically different, as you can see from this PR. I can’t see how I can submit just a quick patch for what you asked for. I’ll have everything ready for you next week and fully working. Promise. 

Sorry for the spam, blame the autism. I’m really verbose.

**Comment by mpentler** [comment]
@brannondorsey I think i am finally ready for you to review this. here is a full list of changes:

- stderr problem fixed
- quiet mode added with the exception of the non-200 error codes
- extensive code refactoring, including moving code into try blocks that doesn't need to run if the initial request fails
- all error checking bar checking for non-200 error codes is in main, as requested
- additionally, error checking made more specific - this can be used as a jumping off point for other handling.
- added a basic banner on load which can be changed as needed
- readme updated
- probably something else i forgot

Thanks for the opportunity, your patience, and I'm sorry this dragged on a bit :p

**Comment by brannondorsey** [comment]
Great! I'll review it this weekend :+1:

**Comment by brannondorsey** [comment]
I just got triggered the following error:

```
XAkQin7d
tSBcKUcw
QRvtER1k
fjcj3354
JcXAJwBw
[*] Total pastes downloaded this session: 648
[*] Waiting 60 seconds before next paste scrape
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "pastebin-mirror/__main__.py", line 169, in <module>
    main()
  File "pastebin-mirror/__main__.py", line 156, in main
    last_scrape = archive_scrape_pastes(last_scrape, scraper, storage, args.rate, args.quiet)
  File "pastebin-mirror/__main__.py", line 57, in archive_scrape_pastes
    recent_pastes = [x for x in scraper.get_recent_pastes() \
  File "pastebin-mirror/scraper.py", line 52, in get_recent_pastes
    return paste_list.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 800, in json
    self.content.decode(encoding), **kwargs
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Steps to reproduce:
1) Launch `pastebin-mirror` from a whitelisted IP address
2) Once archiving, change your IP address to a non-whitelisted IP via a VPN (or other method)

**Comment by mpentler** [comment]
Annoyingly I can only test the trending stuff as I don’t have the premium mode...

I’m having to test on trending, then clone the code for non-trending.

**Comment by mpentler** [comment]
Is this related maybe to another bug? There's nothing changed in the code that significantly differs from your original work I think?

Maybe this one? https://github.com/brannondorsey/pastebin-mirror/issues/1

Would it be worth testing the same thing on your current master branch and seeing if it's present in there too. That'll help narrow it down.

**Comment by brannondorsey** [comment]
Ah, yes, right you are. My apologies for sounding the alarm without properly investigating this first. I'll look into it, I believe it doesn't have anything to do with your contributions.

Bummer about the trending only testing. I'm sorry about that. I'd offer to lend you my pro account, but unfortunately you can only whitelist one IP and I've been archiving for a few months and don't want to terminate the process. 

Sorry I've been slow to take a look at these edits. This weekend was a bit crazier than I expected and now I'm out of town until next week. I'm still planning on going through these edits, just bare with me ;)

Out of curiosity, how much have you tested the proposed changes? And do you have changes that effect non-trending pastes that you haven't been able to test?

**Comment by mpentler** [comment]
I managed to test every exception handler by doing things like changing the scrape URLs, intentionally opening files that were non-existent or renaming the SQL dB file, things like that.

Code that does the counting/quiet mode handling was tested in full on the trending side and then simply ported over - no reason why it shouldn’t work but I guess you can’t be too careful.

And then the rest of the changes are just moving your existing code about into more logical blocks/order, so again it should be fine on that front. 

Are there any suggestions you have for how to test more? I found it hard to generate conditions for testing exceptions and wondered if there was some easy tool to do that.

**Comment by brannondorsey** [comment]
Finally getting around to review these changes. They are looking good so far :+1:. Merge should be coming in the next few days!

**Comment by brannondorsey** [comment]
Merged, thanks again for the contributions!

**Comment by mpentler** [comment]
No problem! I hope it’s all ok!

**Pull request merged**
